build:
	g++ -std=c++11 -O2 -Wall -Wextra ./*.cpp ../3_2_1_3_Initializing_Containers/Vector.o -o app

run:
	./app

clean:
	rm -f app app.i

prep:
	g++ -E -std=c++11 ./*.cpp ../3_2_1_3_Initializing_Containers/Vector.o > app.i